CFLAGS = -fopenmp -O3

all: 

bubblesort: bubblesort.cpp
	$(CXX) bubblesort.cpp -o bubblesort $(CFLAGS)

evenoddsort: evenoddsort.cpp
	$(CXX) evenoddsort.cpp -o evenoddsort $(CFLAGS)

counteven: counteven.cpp
	$(CXX) counteven.cpp -o counteven $(CFLAGS)

multmatrix: multmatrix.cpp
	$(CXX) multmatrix.cpp -o multmatrix.cpp $(CFLAGS)

clean:
	rm -f bubblesort evenoddsort counteven multmatrix
